export enum AutoUpdaterMessages {
  UPDATE_AVAILABLE = 'update-available',
  UPDATE_DOWNLOADED = 'update-downloaded'
}

export const ipcEndpoints = {
  GET_APP_VERSION: 'GET_APP_VERSION',
  OPEN_DIRECTORY_PICKER: 'OPEN_DIRECTORY_PICKER',
  GET_DOCUMENTS_PATH: 'GET_DOCUMENTS_PATH',
  GET_FONTS: 'GET_FONTS',
  UPDATE_THEME: 'UPDATE_THEME',

  // Auto updater
  AUTO_UPDATER: 'AUTO_UPDATER',
  CHECK_FOR_UPDATES: 'CHECK_FOR_UPDATES',
  INSTALL_UPDATE: 'INSTALL_UPDATE',

  // Recording
  SAVE_AUDIO_RECORDING_VERSE: 'SAVE_AUDIO_RECORDING_VERSE',
  GET_AUDIO_RECORDING_VERSE: 'GET_AUDIO_RECORDING_VERSE',
  DELETE_AUDIO_RECORDING_VERSE: 'DELETE_AUDIO_RECORDING_VERSE',
  EXPORT_AUDIO_RECORDINGS: 'EXPORT_AUDIO_RECORDINGS',

  // Text translation
  EXPORT_TEXT_TRANSLATION_AS_HTML: 'EXPORT_TEXT_TRANSLATION_AS_HTML',
  EXPORT_TEXT_TRANSLATION_AS_USFM: 'EXPORT_TEXT_TRANSLATION_AS_USFM',

  GET_PLATFORM: 'GET_PLATFORM',

  // Store
  GET_SETTINGS: 'GET_SETTINGS',
  SET_SETTINGS: 'SET_SETTINGS',
  DELETE_SETTINGS: 'DELETE_SETTINGS',

  // DB Execute
  DB_EXECUTE: 'DB_EXECUTE'
} as const

export enum PanelTypes {
  // project
  TEXT_TRANSLATION_PROJECT = 'text-translation-project',
  AUDIO_PROJECT = 'audio-project',

  // reference
  TEXT_TRANSLATION_REFERENCE = 'text-translation-reference'
}
